

export default Strings = {
    Home: {
        search: 'Search',
        selectLocation: 'Select delivery location',
        flowersReviews: 'Customer Reviews',
        reviews: 'Reviews',
        orderOn: 'Order On : ',
        buyerName: 'Buyer Name : ',
        selectD: 'Select Delivery Location',
        selectaProductAvailability: 'Select a delivery location to see product availability',
        withinLoc: 'Within ',
        outsideLoc: 'Outside ',
        continueShopping: 'CONTINUE SHOPPING',
        continueWA: 'SKIP TO CART',
        viewCollection: 'View Collection',
        luxuryFlowers: 'Luxury Flowers',
        samdayDelivery: 'Same Day Delivery.. Order Now',
        google: 'Google',
        rating: 'Rating: ',
        trustpilot: 'Trustpilot',
        website: 'Website',
        genuineReactionVideos: '*Genuine Reaction Videos',
        exploreMore: 'Explore More',
        earliestDelivery: 'Earliest Delivery:',
        loadMore: 'Load more'
    },
    SignIn: {
        welcome: "Welcome",
        loginToContinue: "Login to continue!",
        mailPlaceHolder: "Email address",
        passPlaceHolder: "Your Password",
        forgotPass: "Forgot Password?",
        createAccount: "Create Account",
        login: "LOGIN",
        loginWithOtp: "LOGIN WITH OTP",
        or: "OR",
        signUpWithFB: "Signup with Facebook",
        signInWithFB: "Sign in with Facebook",
        signUpWithGoogle: "Signup with Google",
        signInWithGoogle: "Sign in with Google",
    },
    SignUp: {
        signup: "Signup",
        signupToGetStart: "Signup to get started!",
        email: "Email",
        password: "Password",
        confirmPassword: "Confirm Password",
        firstName: "First Name",
        lastName: "Last Name",
        mobileNumber: "Mobile Number",
        SIGNUP: "SIGN UP",
        alreadyMember: "Already a member ?",
        loginNow: "Login Now",
    },
    Otp: {
        otp: "OTP",
        getCode: "Get a code?",
        codeSend: "Code is sent to email ",
        notReceiveCode: "I did not receive a code",
        reSend: "RESEND",
        continue: "CONTINUE",
        emptyOtp: 'Please enter OTP.',
        lenghtOtp: 'OTP must be 6 characters long.'
    },
    ForgotPassword: {
        email: "Email",
        ForgotPassword: "Forgot Password",
        resetPass: "RESET PASSWORD"
    },
    ChangePassword: {
        changePassword: "Change Password",
        newPassword: "New Password",
        confirmPassword: "Confirm Password",
        reTypePassword: "Re-type Password",
        passwordsContain: "Passwords must contain:",
        newPaasPlaceHolder: "Enter new password",
        reTypePaasPlaceHolder: "Re-Enter new password",
        atLeast8: "At least 8 characters",
        atLeast1Up: "At least 1 upperr case letter(A....Z)",
        atLeast1Lo: "At least 1 lower case letter(a....z)",
        atLeast1Nu: "At least 1 number (0....9)",
        speacialChar: "At least 1 speacial character (!@#$%^&*)"
    },
    MyProfile: {
        myProfile: "My Profile",
        mobileNumber: "Mobile number",
        emailAddress: "Email address",
        address: "Address",
        receipientAddress: "Recipient Address",
        country: "Country",
        city: "City",
        edit: "EDIT",

    },
    EditMyprofile: {
        address: "Address",
        vatNumber: "GSTIN / VAT Number",
        save: "SAVE",
        changePicture: "Change picture",
        gender: "Gender",
        state: "State",
        dob: "Date of Birth",
        companyName: "Company Name",
        altEmail: "Alternative Email",
        altNumber: "Alternative Contact",
        dateAnniversary: "Date of Anniversary",
        area: "Area",
        clear: "CLEAR",
        selectAnnivarsaryDate: "Select Anniversary Date",
    },
    AddAddress: {
        addAddress: "Add Address",
        editAddress: "Edit Address",
        shippingAddress: "SHIPPING ADDRESS",
        mobile: "Mobile",
        firstName: "First Name",
        lastName: "Last Name",
        billingDetail: "BILLING DETAILS",
        zipCode: "Zipcode",
        zipCodePlaceHolder: "Your zipcode",
        altMobileNum: "Alt Mobile No",
        country: 'Country',
        city: 'City',
    },
    AllowNotification: {
        allowNotification: "YES,ALLOW NOTIFICATIONS",
        updateStatus: "Get updates on your order status!",
        allowDetail: "Allow push notifications to get real-time updates on your order status."
    },
    CartEmpty: {
        nothingHere: "THERE'S NOTHING HERE!",
        discoverMore: "Discover what's appealing",
        toYou: "to you from thousands products and by it easlies.",
        backToHome: "BACK TO HOME"
    },
    SucessMessage: {
        congratulations: "Congratulations!",
        orderDetail: "Your order has been Confirmed!",
        orderId: "Order id :",
        trackOrder: "TRACK YOUR ORDER"
    },
    SelectAddress: {
        selectAddress: "Select Address",
        SELECTADDRESS: "SELECT ADDRESS",
        emailplaceHolder: "Enter Email",
        billingAdd: 'Billing Address',
        plAddress: 'Enter Address',
        proceedToPayment: 'PROCEED TO PAYMENT'
    },
    AddNewReminder: {
        addNewReminder: "Add New Reminder",
        occasion: "Occasion",
        country: "Country",
        date: "Date",
        earlyReminder: "Early Reminder",
        notes: "Notes",
        submit: "SUBMIT",

    },
    detail: {
        addToCart: "Add To Cart",
        GIFTADDONS: "Make It Extra Special",
        upgradeOption: "Upgrade Options",
        selectCity: "Choose City",
        selectTime: "Select Time",
        satisfaction100: "100% Satisfaction guaranteed.",
        satisfactionDetail: "commited to making you and your loved ones happy.",
        hassleFreeDelivery: "Hassle free delivery.",
        hassleFreeDeliveryDetail: "Sending same-day flowers to celebrate a special occasion.",
        deliveryUnit: "Delivery Unit",
        freshFlower: "Fresh Flowers Delivery.",
        freshDetail: "We deliver fresh flowers all over the United Arab Emirates.",
        description: "Description",
        careGuide: "Care Guide",
        flowerCareUnit: "Delivery Information",
        productCode: "Product Code: # 5364",
        productCodeDes: "20 stems of red roses with fillers in a cube black box with a red ribbon.",
        selectDeliveryType: "Select Delivery Type",
        selectDate: "Select date",
        upgradeOptionAvailable: "Upgrade Option",
        giftAddons: 'Gift-Addons',
        freeShiping: 'free_shiping',
        freeCake: 'free_cake',
        freeChocolate: 'free_chocolate',
        freeGlassVase: 'free_glass_vase',
        glassVase: 'Arrange in Glass Vase :',
        cakeEggless: 'Make Cake Eggless :',
        recommendedForYou: 'Recommended For You',
        seeWhatOtherCustomers: 'See What Other Customers Are Buying'
    },
    ShoppingCart: {
        shoppingCart: "Shopping Cart",
        deliveryChargesWithPrice: "Delivery Charges : ",
        deliveryDate: "Delivery Date : ",
        deliveryTime: "Delivery Time : ",
        deliveryCity: "Delivery City : ",
        addPersonalizedMessage: "Add Personalized Message",
        discount: "Discount",
        enterCouponCode: "Enter Coupon Code",
        apply: "APPLY",
        remove: "REMOVE",
        orderSummary: "Order Summary",
        cart: "Cart",
        total: "Total",
        cartId: "Cart- ",
        proceedToCheckout: "PROCEED TO CHECKOUT",
        selectOccasion: "Select Occasion",
        message: "Message",
        senderName: "Sender Name",
        viewMoreCoupon: "View more coupons",
        clear: "Clear",
        submit: "Submit",
        continueShopping: "Continue Shopping",
        maxCharacters: 'max characters: ',
        coutinue: 'Continue',
        enterMessage: 'Enter Message',
        enterSenderName: "Enter Sender's Name",
        cartMessage: 'Message Cart'
    },

    AddressBook: {
        title: "Address Book",
        addNewAddress: "+ ADD NEW ADDRESS"
    },
    Calender: {
        reminder: "Reminder",
        name: "Name",
        country: "Country",
        occassion: "Occassion",
        date: "Date",
        addNewReminder: "ADD NEW REMINDER",
        deleteComment: "You won't be able to revert this!"
    },
    OrderHistory: {
        orderHistory: 'My Order',
        totalAmount: "Total amount : ",
        orderId: 'Order id',
        contactNo: 'Contact No: ',
        productId: 'Product ID: ',
        qty: 'Qty: ',
        options: 'Options: ',
        orderID: ' Order ID : ',
        selectedAlphabet: 'Selected Alphabet : ',
        personalisedImage: 'Personalised Image : '
    },
    CouponCode: {
        apply: "Apply Coupon Code",
        applyCoupon: "APPLY COUPON",
    },
    Other: {
        notification: "Notification",
        faq: "FAQ's",
        newPassword: "New Password",
        catchError: 'Something went wrong!',
        proceedTopay: 'PROCEED TO PAYMENT',
        personalizedMessage: 'PERSONALIZED MESSAGE',
        quickFilters: 'Quick Filters:',
        checkProductDelivery: 'Check Product Delivery',
        clicktoChoose: 'Click to Choose',

        SelectDateDeliveryTime: 'Select Date, Delivery & Time',
        swiperBanerHistory: "BloomsFlora is a floral e-commerce brand that thrives on delivering flowers & gifts to more than 450 cities in India. But wait we don’t plan to end it just there, we ‘re currently working on expanding our services!",
        notRecord: 'Not Record Found.',
        paymentFailed: 'Payment Failed',
        oderDescription: 'Your Order No',
        oderDetail: 'has been Received But your payment has been not processed',
        paymentFailedClik: 'Retry Your Payment',
        paymentFailedContect: 'If you have any urgent queries, contact us at support@uaeflowers.com or call +971 506531300',
        NoCouponAvailable: 'No coupon available.',
        allCities: 'All Cities',
        popularCities: 'Popular Cities',
        selectCity: "Select City",
        selectCountry: "Select Country",
        editReminder: "Edit Reminder",
        areyousureremoveitemcart: 'Are you sure you want to remove the item from cart?',
        invalidCoupon: 'Invalid coupon.',
        pleaseEnterCoupon: 'Please enter a coupon code.',
        earliestDelivery: 'Same Day Delivery',
        noSavedAddress: 'No saved address found for selected city.',
        loadeMore: 'Loade More',
        deleteAccountDe: 'Are you sure you want us to delete your account? This will be deleted your account immediately.',
        readMore: 'Read more...',
        trackOder: 'Track Order',
        customerCare: 'Customer Care'
    },
    Dashboard: {
        dashboard: 'Dashboard',
    },
    Payment: {
        payment: "Payment",
        orderNo: "Order No",
        totalAmount: "Total Amount",
        DeliveryDetails: "Delivery Details",
        OrderSummary: "Order Summary",
        CheckOut: "CHECKOUT"
    },
    PlaceHolder: {
        firstName: "Enter First Name",
        lastName: "Enter Last Name",
        address: "Enter Address",
        mobileNumber: "Enter Mobile number",
        selectCountry: 'Select Country',
        selectCity: 'Select City',
        selectState: 'Select state'

    }
}