const BaseImagePath = '../../assets/Images/';
export default ImagePath = {
    MyAccountMenu: {
        addressbook: require(BaseImagePath + 'MyAccountMenu/addressbook.png'),
        calendar: require(BaseImagePath + 'MyAccountMenu/calendar.png'),
        changepass: require(BaseImagePath + 'MyAccountMenu/changepass.png'),
        order: require(BaseImagePath + 'MyAccountMenu/order.png'),
        wishlist: require(BaseImagePath + 'MyAccountMenu/wishlist.png'),
        ratting: require(BaseImagePath + 'MyAccountMenu/ratting.png'),
        edit: require(BaseImagePath + 'MyAccountMenu/edit.png'),
        crossPink: require(BaseImagePath + 'MyAccountMenu/cross-pink.png'),
        addReminderGold: require(BaseImagePath + 'MyAccountMenu/addReminderGold.png'),
        addressBookGold: require(BaseImagePath + 'MyAccountMenu/addressBookGold.png'),
        changePassGold: require(BaseImagePath + 'MyAccountMenu/changePassGold.png'),
        dasbhoardGold: require(BaseImagePath + 'MyAccountMenu/dasbhoardGold.png'),
        myWishlistGold: require(BaseImagePath + 'MyAccountMenu/muWishlistGold.png'),
        myOderGold: require(BaseImagePath + 'MyAccountMenu/myOderGold.png'),
        rateReviewGold: require(BaseImagePath + 'MyAccountMenu/rateReviewGold.png'),
        reminder: require(BaseImagePath + 'MyAccountMenu/reminder.png'),
        notification: require(BaseImagePath + 'MyAccountMenu/notification.png'),
        logout: require(BaseImagePath + 'MyAccountMenu/logout.png'),

    },
    Drawer: {
        faq: require(BaseImagePath + 'TopMenu/faq.png'),
        return: require(BaseImagePath + 'TopMenu/return.png'),
        contact: require(BaseImagePath + 'TopMenu/contact.png'),
        customer: require(BaseImagePath + 'TopMenu/customer.png'),
        policy: require(BaseImagePath + 'TopMenu/policy.png')
    },
    Bottom: {
        home: require(BaseImagePath + 'BottomBar/home.png'),
        dashboard: require(BaseImagePath + 'BottomBar/category.png'),
        cart: require(BaseImagePath + 'BottomBar/cart.png'),
        homeBlack: require(BaseImagePath + 'BottomBar/homeBlack.png'),
        categoryBlack: require(BaseImagePath + 'BottomBar/categoryBlack.png'),
        cartBlack: require(BaseImagePath + 'BottomBar/cartBlack.png'),
    },
    Auth: {
        fbSign: require(BaseImagePath + 'Auth/facebook.png'),
        googleSign: require(BaseImagePath + 'Auth/google.png'),
        backArrow: require(BaseImagePath + 'Auth/backArrow.png'),
        rightMark: require(BaseImagePath + 'Auth/rightMark.png'),
        hidePassword: require(BaseImagePath + 'Auth/hidePassword.png'),
        openPassword: require(BaseImagePath + 'Auth/openPassword.png'),
    },
    Intro: {
        splash: require(BaseImagePath + 'Intro/splashLogo.png'),
        splashLogoUpdated: require(BaseImagePath + 'Intro/splashLogo-updated.png'),
        // splashLogoUpdated: require(BaseImagePath + 'Intro/splashLogoUpdated.webp'),
    },

    Home: {
        searchIcon: require(BaseImagePath + 'Home/Icon-Search.png'),
        maskGroup: require(BaseImagePath + 'Home/uae-Icon.png'),
        location: require(BaseImagePath + 'Home/Page-1.png'),
        Group: require(BaseImagePath + 'Home/Group.png'),
        arrowNext: require(BaseImagePath + 'Home/Group-Next.png'),
        arrowBack: require(BaseImagePath + 'Home/Group-Back.png'),
        shape: require(BaseImagePath + 'Home/Shape.png'),
        openShape: require(BaseImagePath + 'Home/openShape.png'),
        crossPink: require(BaseImagePath + 'Home/cross-pink.png'),
        close: require(BaseImagePath + 'Home/close.png'),
        heartRed: require(BaseImagePath + 'Home/heartRed.png'),
        menu: require(BaseImagePath + 'Home/menu.png'),
        addon: require(BaseImagePath + 'Home/addon.png'),
        addAddon: require(BaseImagePath + 'Home/addAddon.png'),
        quote_left: require(BaseImagePath + 'Home/quote_left.png'),
    },
    Other: {
        unCheckRadioGrey: require(BaseImagePath + 'Other/unCheckRadioGrey.png'),
        flowersBouquetCamel: require(BaseImagePath + 'Other/flowersBouquetCamel.png'),
        flowersPremiumBlack: require(BaseImagePath + 'Other/flowersPremiumBlack.png'),
        flowersPremium: require(BaseImagePath + 'Other/flowersPremium.png'),
        blankImage: require(BaseImagePath + 'Other/blankImage.png'),
        unCheckRadioBtn: require(BaseImagePath + 'Other/unCheckRadioBtn.png'),
        edit: require(BaseImagePath + 'Other/edit.png'),
        cart: require(BaseImagePath + 'Other/cart.png'),
        closeButton: require(BaseImagePath + 'Other/closeButton.png'),
        notificationBell: require(BaseImagePath + 'Other/notificationBell.png'),
        success: require(BaseImagePath + 'Other/success.png'),
        verifiedSign: require(BaseImagePath + 'Other/verifiedSign.png'),
        saveIcon: require(BaseImagePath + 'Other/saveIcon.png'),
        cameraCamal: require(BaseImagePath + 'Other/camelCamera.png'),
        calendar: require(BaseImagePath + 'Other/calendar.png'),
        searchIcon: require(BaseImagePath + 'Other/searchIcon.png'),
        heartIcon: require(BaseImagePath + 'Other/heart.png'),
        heartRed: require(BaseImagePath + 'Other/heartRed.png'),
        star: require(BaseImagePath + 'Other/star.png'),
        trustpilotStars: require(BaseImagePath + 'Other/trustpilot-stars.png'),
        flower: require(BaseImagePath + 'Other/flower.png'),
        flowerCamel: require(BaseImagePath + 'Other/flowerCamel.png'),
        cartIcon: require(BaseImagePath + 'Other/cart.png'),
        unCheckedBox: require(BaseImagePath + 'Other/unCheckedBox.png'),
        customerRate: require(BaseImagePath + 'Other/customerRate.png'),
        deliveryIcon: require(BaseImagePath + 'Other/deliveryIcon.png'),
        plusIcon: require(BaseImagePath + 'Other/plusIcon.png'),
        minusIcon: require(BaseImagePath + 'Other/minusIcon.png'),
        flowerBouquet: require(BaseImagePath + 'Other/flowerBouquet.png'),
        recycleIcon: require(BaseImagePath + 'Other/recycleIcon.png'),
        singleStar: require(BaseImagePath + 'Other/singleStar.png'),
        telephoneIcon: require(BaseImagePath + 'Other/telephoneIcon.png'),
        unCheckRadioBtnWhite: require(BaseImagePath + 'Other/unCheckRadioBtnWhite.png'),
        correct: require(BaseImagePath + 'Other/correct.png'),
        cutIcon: require(BaseImagePath + 'Other/cutIcon.png'),
        emptyRadio: require(BaseImagePath + 'Other/emptyRadio.png'),
        downFaq: require(BaseImagePath + 'Other/downFaq.png'),
        dashboardBlack: require(BaseImagePath + 'Other/dashboardBlack.png'),
        halfStar: require(BaseImagePath + 'Other/halfStar.png'),
        emptyStar: require(BaseImagePath + 'Other/emptyStar.png'),
        emptyUser: require(BaseImagePath + 'Other/emptyUser.png'),
        heartActive: require(BaseImagePath + 'Other/heartActive.png'),
        offer: require(BaseImagePath + 'Other/offer.png'),
        freeGlassVase: require(BaseImagePath + 'Other/free_glass_vase.png'),
        freeShiping: require(BaseImagePath + 'Other/free_shiping.png'),
        doubleTheFlowersFree: require(BaseImagePath + 'Other/double_the_flowers_free.png'),
        closeCircleBlack: require(BaseImagePath + 'Other/closeCircleBlack.png'),
        deleteBlack: require(BaseImagePath + 'Other/deleteBlack.png'),
        leftarrow: require(BaseImagePath + 'Other/left-arrow.png'),
        rightarrows: require(BaseImagePath + 'Other/right-arrows.png'),
        arrowBack: require(BaseImagePath + 'Other/arrowBack.png'),
        arrowNext: require(BaseImagePath + 'Other/arrowNext.png'),
        personlisedIcon: require(BaseImagePath + 'Other/personlisedIcon.png'),
        radioBlack: require(BaseImagePath + 'Other/radioBlack.png'),
        couponChip: require(BaseImagePath + 'Other/couponChip.png'),
        AllowNotificationNew: require(BaseImagePath + 'Other/AllowNotificationNew.png'),
        filterBlack: require(BaseImagePath + 'Other/filterBlack.png'),
        cancel_payment: require(BaseImagePath + 'Other/cancel_payment.png'),
        checkRadioBtn: require(BaseImagePath + 'Other/checkRadioBtn.png'),
        upArrow: require(BaseImagePath + 'Other/up-arrow.png'),
        downArrow: require(BaseImagePath + 'Other/down-arrow.png'),

        wifi: require(BaseImagePath + 'Other/wifi.png'),
        reload: require(BaseImagePath + 'Other/reload.png'),
        blankImageproduct: require(BaseImagePath + 'Other/blankImageproduct.png'),
        blankImageproductFlora: require(BaseImagePath + 'Other/blankImageproductFlora.png'),
        rupees: require(BaseImagePath + 'Other/rupee.png'),
        rupeeRegular: require(BaseImagePath + 'Other/rupeeRegular.png'),
        bagIcon: require(BaseImagePath + 'Other/bagIcon.png'),
        rightIcon: require(BaseImagePath + 'Other/rightIcon.png'),
        close: require(BaseImagePath + 'Other/close.png'),
        payu: require(BaseImagePath + 'Other/payu.png'),
        paypal: require(BaseImagePath + 'Other/paypal.png'),
        ccavenue: require(BaseImagePath + 'Other/ccavenue.png'),
        razorpay: require(BaseImagePath + 'Other/razorpay.png'),
    },
    webIcons: {
        attachments: require('../../assets/Images/WebpIcon/attachments.png'),
        weddingflowersuae: require('../../assets/Images/WebpIcon/wedding-flowers-uae.jpg'),
        newarrivalgifthampers: require('../../assets/Images/WebpIcon/new-arrival-gift-hampers.jpg'),
        weddingmobile: require('../../assets/Images/WebpIcon/wedding-mobile.webp'),

    }
}